"""
Django settings for djangoapi project.

Generated by 'django-admin startproject' using Django 5.0.4.
"""

from pathlib import Path
import os, sys
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
DJANGO_SUPERUSER_USERNAME=(os.getenv('DJANGO_SUPERUSER_USERNAME'))
BASE_DIR = Path(__file__).resolve().parent.parent
EPSG_FOR_GEOMETRIES=int(os.getenv('EPSG_FOR_GEOMETRIES',4326))
ST_SNAP_PRECISION=float(os.getenv('ST_SNAP_PRECISION',0.0001))
MAX_NUMBER_OF_RETRIEVED_ROWS=int(os.getenv('MAX_NUMBER_OF_RETRIEVED_ROWS',1000))
DJANGO_KNOX_AUTOMATICALLY_REMOVE_TOKENS=os.getenv("DJANGO_KNOX_AUTOMATICALLY_REMOVE_TOKENS", "True").lower() in ('true', '1', 't')

DJANGO_SUPERUSER_EMAIL=os.getenv('DJANGO_SUPERUSER_EMAIL')
FORCE_SCRIPT_NAME=os.getenv('FORCE_SCRIPT_NAME')

API_URL=os.getenv('API_URL')
WEB_URL=os.getenv('WEB_URL', "http://localhost:4200")
TEMPLATE_ASSETS_URL=os.getenv('TEMPLATE_ASSETS_URL')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY','DKLSJGHFHF654165464kasdjhadkgf')

# SECURITY WARNING: don't run with debug turned on in production!
REMOTE_DEBUG = False
DEBUG = os.getenv("DEBUG", 'True').lower() in ('true', '1', 't')

allowed_hosts_str = os.getenv('DJANGO_ALLOWED_HOSTS')
if allowed_hosts_str:
    if allowed_hosts_str == '*':
        ALLOWED_HOSTS = ['*']
    else:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]
else:
    ALLOWED_HOSTS = ['*'] # En desarrollo local permitimos todo

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.gis',
    'corsheaders',
    'rest_framework',
    'rest_framework_gis',
    'knox',
    'django_filters',
    'drf_spectacular',
    'core',
    'codelist',
    'buildings',
    'flowers',
    'accidentes',
    'geoportal',
    'bicicleta'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ESTA ES LA LÍNEA CRÍTICA QUE FALTABA
ROOT_URLCONF = 'djangoapi.urls'

# --- CONFIGURACIÓN DE CORS Y SEGURIDAD PARA EL LOGIN ---
CORS_ALLOW_CREDENTIALS = True  

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [WEB_URL]

SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['core'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoapi.wsgi.application'

# Database configuration
MODE_TEST = os.getenv("MODE_TEST", 'False').lower() in ('true', '1', 't')
if MODE_TEST:
    DATABASE_NAME = 'test_'+ os.getenv('POSTGRES_DB', 'desweb')
else:
    DATABASE_NAME = os.getenv('POSTGRES_DB', 'desweb')

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': DATABASE_NAME,
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
        'OPTIONS': {
            'options': '-c search_path=public',
        }
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if DEBUG:
    LOGIN_URL = "/core/not_loggedin/"
else:
    LOGIN_URL = "/desweb-api/core/not_loggedin/"

# --- CONFIGURACIÓN DE REST FRAMEWORK PARA EL PROYECTO ---
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny' 
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication', # Permite el login por sesión
        'knox.auth.TokenAuthentication',
    ),
    'EXCEPTION_HANDLER': 'core.myLib.drf.custom_exception_handler',
}

REST_KNOX = {
    'TOKEN_TTL': timedelta(days=int(os.getenv("DJANGO_SESSION_EXPIRY_DAYS", 1))),
    'TOKEN_LIMIT_PER_USER': int(os.getenv("TOKEN_LIMIT_PER_USER", 3)),
}

# Email settings
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS','True').lower() == 'true'
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_FROM = os.getenv('EMAIL_FROM')

# Testing configuration
TESTING = 'test' in sys.argv
if TESTING:
     DATABASES['default']['NAME'] = 'test_'+ os.getenv('POSTGRES_DB', 'desweb')
     DATABASES['default']['TEST'] = {
         'NAME': 'test_'+ os.getenv('POSTGRES_DB', 'desweb'),
         'CREATE_DB': False,
     }